import { useState } from "react";
import { Download, FileText, Trash2, Upload } from "lucide-react";
import { Badge, Button, EmptyState, Input, Modal, Select } from "@/shared/ui";
import { useAuth } from "@/modules/auth/hooks/useAuth";
import { useDeleteRecruitmentDocument, useRecruitmentDocuments, useUploadRecruitmentDocument } from "../hooks/useRecruitmentDocuments";
import type { Application, Job, RecruitmentDocument, RecruitmentDocumentType } from "../types";

const OTHER_DOCUMENTS = [
  { value: "EXPERIENCE_CERTIFICATE", label: "Experience Certificate" },
  { value: "PREVIOUS_EMPLOYMENT_LETTER", label: "Previous Employment Letter" },
] as const;

export const RecruitmentDocumentsCard = ({ candidateId, applications, jobs }: { candidateId: number; applications: Application[]; jobs: Job[] }) => {
  const { user } = useAuth(); const canManage = user?.role === "hr";
  const query = useRecruitmentDocuments(candidateId); const upload = useUploadRecruitmentDocument(candidateId); const remove = useDeleteRecruitmentDocument(candidateId);
  const [open, setOpen] = useState(false); const [documentType, setDocumentType] = useState<RecruitmentDocumentType>("RESUME"); const [documentKey, setDocumentKey] = useState("RESUME"); const [applicationId, setApplicationId] = useState(""); const [file, setFile] = useState<File>(); const [error, setError] = useState<string | null>(null);
  const documents = [...(query.data ?? [])].sort((a, b) => Number(b.isCurrent) - Number(a.isCurrent) || b.version - a.version);
  const groups = Array.from(documents.reduce((map, document) => { const key = `${document.applicationId ?? "candidate"}:${document.documentType}:${document.documentKey}`; const versions = map.get(key) ?? []; versions.push(document); map.set(key, versions); return map; }, new Map<string, RecruitmentDocument[]>()).values());
  const applicationLabel = (document: RecruitmentDocument) => jobs.find((job) => job.id === applications.find((item) => item.id === document.applicationId)?.jobId)?.title;
  const view = (document: RecruitmentDocument) => { if (document.fileUrl) { window.open(document.fileUrl, "_blank", "noopener,noreferrer"); return; } const url = URL.createObjectURL(new Blob([`Mock Recruitment document\n${document.fileName}\nVersion ${document.version}`], { type: document.mimeType })); const anchor = window.document.createElement("a"); anchor.href = url; anchor.download = document.fileName; anchor.click(); URL.revokeObjectURL(url); };
  const submit = async () => { if (!file) return; const selected = OTHER_DOCUMENTS.find((option) => option.value === documentKey); setError(null); try { await upload.mutateAsync({ candidateId, applicationId: applicationId ? Number(applicationId) : null, documentType, documentKey: documentType === "RESUME" ? "RESUME" : documentKey, displayName: documentType === "RESUME" ? "Resume" : selected?.label ?? "", file }); setOpen(false); setFile(undefined); setApplicationId(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to upload document"); } };
  const deleteVersion = async (document: RecruitmentDocument) => { if (!window.confirm(`Permanently delete ${document.fileName} version ${document.version}?`)) return; setError(null); try { await remove.mutateAsync(document.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to delete document"); } };
  if (!canManage) return null;
  return <section className="card p-4 sm:p-5"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-base font-medium tracking-wide text-slate-700 dark:text-navy-100">Recruitment Documents</h3><p className="text-xs text-slate-500 dark:text-navy-300">Candidate resumes and Application-specific recruitment files · 10 MB max</p></div><Button size="sm" leftIcon={<Upload className="size-4" />} onClick={() => setOpen(true)}>Upload</Button></div>
    {error && <p className="mb-3 rounded-lg bg-error/10 p-3 text-sm text-error">{error}</p>}{query.isLoading ? <p className="py-6 text-center text-sm text-slate-500">Loading documents…</p> : documents.length === 0 ? <EmptyState icon={FileText} title="No recruitment documents" description="Resume is optional. HR can upload one when available." /> : <div className="space-y-4">{groups.map((versions) => { const logical = versions[0]; return <div key={`${logical.applicationId ?? "candidate"}-${logical.documentKey}`} className="rounded-lg border p-4"><div className="mb-2"><p className="font-semibold">{logical.displayName}</p>{logical.applicationId && <p className="text-xs text-slate-400">Application · {applicationLabel(logical) ?? logical.applicationId}</p>}</div><div className="divide-y divide-slate-100">{versions.map((document) => <div key={document.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><div className="flex items-center gap-2"><p className="text-sm font-medium">V{document.version}</p>{document.isCurrent && <Badge label="Current" variant="success" />}</div><p className="text-xs text-slate-500">{document.fileName} · {(document.fileSize / 1024).toFixed(0)} KB</p><p className="text-xs text-slate-400">{document.createdBy} · {new Date(document.createdAt).toLocaleString()}</p></div><div className="flex gap-1"><Button size="sm" variant="ghost" leftIcon={<Download className="size-3" />} onClick={() => view(document)}>View</Button><Button size="sm" variant="ghost" leftIcon={<Trash2 className="size-3" />} isLoading={remove.isPending} onClick={() => void deleteVersion(document)}>Delete</Button></div></div>)}</div></div>; })}</div>}
    <Modal isOpen={open} onClose={() => { setOpen(false); setError(null); }} title="Upload Recruitment document" footer={<><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={!file || (documentType === "OTHER" && (!applicationId || !documentKey))} isLoading={upload.isPending} onClick={() => void submit()}>Upload</Button></>}><div className="space-y-4"><Select label="Document type" required value={documentType} options={[{ value: "RESUME", label: "Resume / new Resume version" }, { value: "OTHER", label: "Other Application document" }]} onChange={(event) => { const type = event.target.value as RecruitmentDocumentType; setDocumentType(type); setDocumentKey(type === "RESUME" ? "RESUME" : OTHER_DOCUMENTS[0].value); if (type === "RESUME") setApplicationId(""); }} />{documentType === "OTHER" && <><Select label="Document" required value={documentKey} options={OTHER_DOCUMENTS} onChange={(event) => setDocumentKey(event.target.value)} /><Select label="Application" required value={applicationId} placeholder="Select Application" options={applications.map((application) => ({ value: String(application.id), label: jobs.find((job) => job.id === application.jobId)?.title ?? `Application ${application.id}` }))} onChange={(event) => setApplicationId(event.target.value)} /></>}<Input label="File" required type="file" accept=".pdf,.doc,.docx,.odt,.jpg,.jpeg,.png" onChange={(event) => setFile(event.target.files?.[0])} />{error && <p className="text-sm text-error">{error}</p>}</div></Modal>
  </section>;
};
