import { DOCUMENT_CATEGORY_OPTIONS, DOCUMENT_TYPE_OPTIONS, type DocumentCategoryType, type DocumentType, type EmployeeDocument } from "../types/document.type";
const wait=()=>new Promise(resolve=>setTimeout(resolve,120));
let documents:EmployeeDocument[]=[{id:"doc-1",employee_id:"emp-1",document_category:"resume",document_name:"resume",document_description:"Current resume",file_name:"Aarav_Mehta_Resume.pdf",file_url:"",file_size:"1.8 MB",file_type:"application/pdf",uploaded_at:"2026-08-03T10:00:00Z",uploaded_by:"HR Administrator",archived:false,version:2,versions:[{version:1,file_name:"Aarav_Resume_2025.pdf",uploaded_at:"2025-08-03T10:00:00Z",uploaded_by:"HR Administrator"},{version:2,file_name:"Aarav_Mehta_Resume.pdf",uploaded_at:"2026-08-03T10:00:00Z",uploaded_by:"HR Administrator"}]}];
export interface DocumentInput{document_category:DocumentCategoryType;document_name:DocumentType;document_description?:string;file:File}
const ensureFile=(file:File)=>{const extensions=["pdf","doc","docx","odt","jpg","jpeg","png"];const extension=file.name.split(".").pop()?.toLowerCase();if(!extension||!extensions.includes(extension))throw new Error("Upload PDF, DOC, DOCX, ODT, JPG, JPEG, or PNG");if(file.size>10*1024*1024)throw new Error("File size must not exceed 10 MB")};
const find=(employeeId:string,documentId:string)=>{const row=documents.find(item=>item.employee_id===employeeId&&item.id===documentId);if(!row)throw new Error("Document not found");return row};
export const empDocumentApi={
 async getDocuments(employeeId:string){await wait();return structuredClone(documents.filter(item=>item.employee_id===employeeId))},
 async uploadDocument(employeeId:string,input:DocumentInput){await wait();ensureFile(input.file);const now=new Date().toISOString();const row:EmployeeDocument={id:`doc-${Date.now()}`,employee_id:employeeId,document_category:input.document_category,document_name:input.document_name,document_description:input.document_description,file_name:input.file.name,file_url:"",file_size:`${Math.ceil(input.file.size/1024)} KB`,file_type:input.file.type||"application/octet-stream",uploaded_at:now,uploaded_by:"HR Administrator",archived:false,version:1,versions:[{version:1,file_name:input.file.name,uploaded_at:now,uploaded_by:"HR Administrator"}]};documents=[...documents,row];return structuredClone(row)},
 async updateMetadata(employeeId:string,documentId:string,input:{document_category:DocumentCategoryType;document_name:DocumentType;document_description?:string}){await wait();const category=DOCUMENT_CATEGORY_OPTIONS.find(item=>item.value===input.document_category);const name=DOCUMENT_TYPE_OPTIONS.find(item=>item.value===input.document_name);if(!category||!name||name.category_id!==category.category_id)throw new Error("Select a valid document category and name");const row=find(employeeId,documentId);Object.assign(row,input);return structuredClone(row)},
 async replace(employeeId:string,documentId:string,file:File){await wait();ensureFile(file);const row=find(employeeId,documentId);const now=new Date().toISOString();row.version+=1;row.file_name=file.name;row.file_size=`${Math.ceil(file.size/1024)} KB`;row.file_type=file.type||"application/octet-stream";row.uploaded_at=now;row.versions.push({version:row.version,file_name:file.name,uploaded_at:now,uploaded_by:"HR Administrator"});return structuredClone(row)},
 async setArchived(employeeId:string,documentId:string,archived:boolean){await wait();const row=find(employeeId,documentId);row.archived=archived;return structuredClone(row)},
};
