import type { BankAccount, BulkLifecycleInput, BulkOrganizationInput, ChangeLifecycleInput, CorrectEmployeeCodeInput, CreateEmployeeInput, Employee, EmployeeExportInput, EmployeeExportResult, EmployeeListParams, EmployeeListResult, EmployeeMasters, ReplaceBankInput, StatutoryRecord, TransferEmployeeInput, UpdateOrganizationInput, UpdateProfileInput, UpdateReportingManagerInput, UpdateStatutoryInput } from "../types/employee.type";

const wait = () => new Promise((resolve) => setTimeout(resolve, 120));
const now = "2026-08-20T10:00:00.000Z";
export const employeeMasters: EmployeeMasters = {
  companies: [{ id: 1, name: "PeoplePulse Technologies", prefix: "PPT" }, { id: 2, name: "Northstar Services", prefix: "NSS" }],
  branches: [{ id: "b1", companyId: 1, name: "Ahmedabad", status: "active" }, { id: "b2", companyId: 1, name: "Mumbai", status: "active" }, { id: "b3", companyId: 1, name: "Vadodara (Legacy)", status: "inactive" }, { id: "b4", companyId: 2, name: "Bengaluru", status: "active" }],
  departments: [{ id: "d1", companyId: 1, name: "Engineering", status: "active" }, { id: "d2", companyId: 1, name: "People Operations", status: "active" }, { id: "d3", companyId: 2, name: "Customer Success", status: "active" }],
  designations: [{ id: "g1", companyId: 1, name: "Software Engineer", status: "active" }, { id: "g2", companyId: 1, name: "HR Executive", status: "active" }, { id: "g3", companyId: 2, name: "Success Manager", status: "active" }],
  weekOffs: [{ id: "w1", companyId: 1, name: "General Staff", status: "active" }, { id: "w2", companyId: 1, name: "Legacy Production", status: "inactive" }, { id: "w3", companyId: 2, name: "Support", status: "active" }],
  holidayLists: [{ id: "h1", companyId: 1, name: "India 2026", status: "active" }, { id: "h2", companyId: 1, name: "Legacy 2025", status: "inactive" }, { id: "h3", companyId: 2, name: "India Support 2026", status: "active" }],
};
const address = { line1: "12 Business Park", city: "Ahmedabad", state: "Gujarat", country: "India", pincode: "380015" };
const make = (id: string, code: string, firstName: string, lastName: string, status: Employee["lifecycleStatus"], overrides: Partial<Employee> = {}): Employee => ({
  id, companyId: 1, company: "PeoplePulse Technologies", employeeCode: code, branchId: "b1", branch: "Ahmedabad", departmentId: "d1", department: "Engineering", designationId: "g1", designation: "Software Engineer", weekOffMasterId: "w1", weekOffMaster: "General Staff", holidayListMasterId: "h1", holidayListMaster: "India 2026", firstName, lastName, fullName: `${firstName} ${lastName}`, personalEmail: `${firstName.toLowerCase()}.${lastName.toLowerCase()}@example.com`, phone: "9876543210", dob: "1993-05-12", aadhaarName: `${firstName} ${lastName}`, aadhaarNumber: "123456789012", pan: "ABCDE1234F", permanentAddress: address, correspondenceAddress: address, emergencyContact: { name: "Primary Contact", phone: "9898989898", relationship: "Parent" }, joiningDate: "2024-01-10", lifecycleStatus: status, accountSummary: { state: status === "resigned" ? "fnf_pending" : "active", officeEmail: `${firstName.toLowerCase()}@peoplepulse.test` }, payrollSummary: { ctcLabel: "Payroll summary available", latestPayslip: "July 2026", taxYear: "2026-27" }, attendanceSummary: { presentDays: 19, absentDays: 1, pendingRegularizations: 1 }, leaveSummary: { available: 14, used: 6, pending: 1 }, assetsSummary: { assigned: 2, labels: ["Laptop", "Access card"] }, history: [], createdAt: now, updatedAt: now, ...overrides,
});
let employees: Employee[] = [
  make("emp-1", "PPT-0001", "Aarav", "Mehta", "regular", { gender: "Male", bloodGroup: "B+", reportingManager: { id: "emp-2", name: "Meera Shah" }, recruitmentProvenance: { source: "Campus Hiring", candidateId: "CAN-1042", offerId: "OFF-501" }, history: [{ id: "hist-1", field: "branch", previousValue: "Vadodara", currentValue: "Ahmedabad", changedBy: "HR Administrator", changedAt: "2026-03-12T09:30:00Z", reason: "Team relocation" }, { id: "hist-2", field: "bank", previousValue: "State Bank of India", currentValue: "HDFC Bank", changedBy: "HR Administrator", changedAt: "2025-04-01T09:30:00Z", reason: "Employee bank change request" }] }),
  make("emp-2", "PPT-0002", "Meera", "Shah", "probation", { departmentId: "d2", department: "People Operations", designationId: "g2", designation: "HR Executive" }),
  make("emp-3", "PPT-0003", "Kabir", "Patel", "notice_period", { noticeStartDate: "2026-08-01", endDate: "2026-09-15" }),
  make("emp-4", "PPT-0004", "Nisha", "Rao", "resigned", { endDate: "2026-07-31", resignationDate: "2026-06-20" }),
  make("emp-5", "PPT-0005", "Dev", "Joshi", "temp", { branchId: "b3", branch: "Vadodara (Legacy)", weekOffMasterId: "w2", weekOffMaster: "Legacy Production", holidayListMasterId: "h2", holidayListMaster: "Legacy 2025" }),
  make("emp-6", "NSS-0001", "Ira", "Nair", "regular", { companyId: 2, company: "Northstar Services", branchId: "b4", branch: "Bengaluru", departmentId: "d3", department: "Customer Success", designationId: "g3", designation: "Success Manager", weekOffMasterId: "w3", weekOffMaster: "Support", holidayListMasterId: "h3", holidayListMaster: "India Support 2026" }),
];
const banks = new Map<string, BankAccount[]>([["emp-1", [{ id: "bank-2", accountNumber: "9876543210", accountHolder: "Aarav Mehta", bankName: "HDFC Bank", branchName: "Ahmedabad", ifsc: "HDFC0001234", active: true, effectiveFrom: "2025-04-01" }, { id: "bank-1", accountNumber: "1234567890", accountHolder: "Aarav Mehta", bankName: "State Bank of India", branchName: "Vadodara", ifsc: "SBIN0004567", active: false, effectiveFrom: "2024-01-10" }]]]);
const statutory = new Map<string, StatutoryRecord>([["emp-1", { uan: "100200300400", pfNumber: "GJ1234567", pfJoiningDate: "2024-01-10", esicNumber: "ESIC009988", esicJoiningDate: "2024-01-10" }]]);
const clone = <T,>(value: T): T => structuredClone(value);
const required = (value: string, label: string) => { if (!value.trim()) throw new Error(`${label} is required`); };
const master = (items: EmployeeMasters[keyof Omit<EmployeeMasters, "companies">], id: string, companyId: number) => items.find((item) => item.id === id && item.companyId === companyId && item.status === "active");
const findEmployee = (id: string) => { const row = employees.find((employee) => employee.id === id); if (!row) throw new Error("Employee not found"); return row; };
const history = (field: string, previousValue: string, currentValue: string, reason?: string) => ({ id: `hist-${Date.now()}-${field}`, field, previousValue, currentValue, changedBy: "HR Administrator", changedAt: new Date().toISOString(), reason });
export const employeeMockRepository = {
  async list(params: EmployeeListParams): Promise<EmployeeListResult> { await wait(); let rows = employees.filter((e) => e.companyId === params.companyId); const q = params.search?.trim().toLowerCase(); if (q) rows = rows.filter((e) => [e.employeeCode, e.firstName, e.lastName, e.fullName, e.personalEmail, e.phone, e.department, e.designation, e.branch].some((v) => v.toLowerCase().includes(q))); if (params.statuses.length) rows = rows.filter((e) => params.statuses.includes(e.lifecycleStatus)); if (params.branchIds.length) rows = rows.filter((e) => params.branchIds.includes(e.branchId)); if (params.departmentIds.length) rows = rows.filter((e) => params.departmentIds.includes(e.departmentId)); if (params.designationIds.length) rows = rows.filter((e) => params.designationIds.includes(e.designationId)); rows.sort((a, b) => String(a[params.sortBy]).localeCompare(String(b[params.sortBy])) * (params.sortDirection === "asc" ? 1 : -1)); const start = (params.page - 1) * params.pageSize; return clone({ items: rows.slice(start, start + params.pageSize), total: rows.length, page: params.page, pageSize: params.pageSize }); },
  async get(id: string) { await wait(); return clone(findEmployee(id)); },
  async masters() { await wait(); return clone(employeeMasters); },
  async create(input: CreateEmployeeInput) { await wait(); [input.firstName, input.lastName, input.personalEmail, input.phone, input.dob, input.aadhaarName, input.aadhaarNumber, input.pan, input.joiningDate, input.emergencyContact.name, input.emergencyContact.phone, input.emergencyContact.relationship].forEach((v, i) => required(v, `Required field ${i + 1}`)); const company = employeeMasters.companies.find((c) => c.id === input.companyId); const branch = master(employeeMasters.branches, input.branchId, input.companyId); const department = master(employeeMasters.departments, input.departmentId, input.companyId); const designation = master(employeeMasters.designations, input.designationId, input.companyId); const weekOff = master(employeeMasters.weekOffs, input.weekOffMasterId, input.companyId); const holiday = master(employeeMasters.holidayLists, input.holidayListMasterId, input.companyId); if (!company || !branch || !department || !designation || !weekOff || !holiday) throw new Error("Select active masters from the chosen company"); const sequence = employees.filter((e) => e.companyId === input.companyId).length + 1; const id = `emp-${Date.now()}`; const row = make(id, `${company.prefix}-${String(sequence).padStart(4, "0")}`, input.firstName, input.lastName, input.lifecycleStatus, { ...input, company: company.name, branch: branch.name, department: department.name, designation: designation.name, weekOffMaster: weekOff.name, holidayListMaster: holiday.name, fullName: [input.firstName, input.middleName, input.lastName].filter(Boolean).join(" "), accountSummary: { state: "not_created" } }); employees = [...employees, row]; banks.set(id, [{ ...input.bank, id: `bank-${Date.now()}`, active: true, effectiveFrom: input.joiningDate }]); return clone(row); },
  async changeLifecycle(id: string, input: ChangeLifecycleInput) { const row = await this.get(id); if (input.status === "notice_period" && !input.endDate) throw new Error("Last working date is required"); if (input.status === "resigned" && (!input.endDate || !input.resignationDate)) throw new Error("Resignation and last working dates are required"); const updated = { ...row, ...input, lifecycleStatus: input.status, accountSummary: input.status === "resigned" ? { ...row.accountSummary, state: "fnf_pending" as const } : row.accountSummary, updatedAt: new Date().toISOString(), history: [...row.history, { id: `hist-${Date.now()}`, field: "lifecycleStatus", previousValue: row.lifecycleStatus, currentValue: input.status, changedBy: "HR Administrator", changedAt: new Date().toISOString(), reason: input.reason }] }; employees = employees.map((e) => e.id === id ? updated : e); return clone(updated); },
  async correctCode(id: string, input: CorrectEmployeeCodeInput) { required(input.newCode, "New code"); required(input.reason, "Reason"); const row = await this.get(id); if (employees.some((e) => e.companyId === row.companyId && e.employeeCode === input.newCode && e.id !== id)) throw new Error("Employee code already exists in this company"); const updated = { ...row, employeeCode: input.newCode, updatedAt: new Date().toISOString(), history: [...row.history, { id: `hist-${Date.now()}`, field: "employeeCode", previousValue: row.employeeCode, currentValue: input.newCode, changedBy: "HR Administrator", changedAt: new Date().toISOString(), reason: input.reason }] }; employees = employees.map((e) => e.id === id ? updated : e); return clone(updated); },
  async updateProfile(id: string, input: UpdateProfileInput) { await wait(); const row = findEmployee(id); if (row.lifecycleStatus === "resigned") throw new Error("Closed employees cannot use normal profile edit"); [input.firstName,input.lastName,input.personalEmail,input.phone,input.dob,input.aadhaarName,input.aadhaarNumber,input.pan,input.emergencyContact.name,input.emergencyContact.phone,input.emergencyContact.relationship].forEach((value,index)=>required(value,`Required field ${index+1}`)); const updated={...row,...input,fullName:[input.firstName,input.middleName,input.lastName].filter(Boolean).join(" "),updatedAt:new Date().toISOString()}; employees=employees.map(e=>e.id===id?updated:e); return clone(updated); },
  async updateOrganization(id: string, input: UpdateOrganizationInput) { await wait(); required(input.reason,"Reason"); const row=findEmployee(id); if(row.lifecycleStatus==="resigned") throw new Error("Closed employees cannot use normal organization edit"); const branch=master(employeeMasters.branches,input.branchId,row.companyId); const department=master(employeeMasters.departments,input.departmentId,row.companyId); const designation=master(employeeMasters.designations,input.designationId,row.companyId); const weekOff=master(employeeMasters.weekOffs,input.weekOffMasterId,row.companyId); const holiday=master(employeeMasters.holidayLists,input.holidayListMasterId,row.companyId); if(!branch||!department||!designation||!weekOff||!holiday) throw new Error("Select active masters from the employee company"); const changes=[...[row.branch!==branch.name?history("branch",row.branch,branch.name,input.reason):null,row.department!==department.name?history("department",row.department,department.name,input.reason):null,row.designation!==designation.name?history("designation",row.designation,designation.name,input.reason):null].filter(Boolean)]; const updated:Employee={...row,branchId:branch.id,branch:branch.name,departmentId:department.id,department:department.name,designationId:designation.id,designation:designation.name,weekOffMasterId:weekOff.id,weekOffMaster:weekOff.name,holidayListMasterId:holiday.id,holidayListMaster:holiday.name,history:[...row.history,...changes] as Employee["history"],updatedAt:new Date().toISOString()}; employees=employees.map(e=>e.id===id?updated:e); return clone(updated); },
  async replaceBank(id:string,input:ReplaceBankInput){await wait();const employee=findEmployee(id);required(input.accountNumber,"Account number");required(input.reason,"Reason");const previous=banks.get(id)??[];const oldBank=previous.find(account=>account.active)?.bankName??"Not recorded";const next=previous.map(account=>({...account,active:false}));next.unshift({id:`bank-${Date.now()}`,accountNumber:input.accountNumber,accountHolder:input.accountHolder,bankName:input.bankName,branchName:input.branchName,ifsc:input.ifsc,active:true,effectiveFrom:input.effectiveFrom});banks.set(id,next);const updated={...employee,history:[...employee.history,history("bank",oldBank,input.bankName,input.reason)],updatedAt:new Date().toISOString()};employees=employees.map(row=>row.id===id?updated:row);return clone(next);},
  async updateStatutory(id:string,input:UpdateStatutoryInput){await wait();findEmployee(id);statutory.set(id,{...input});return clone(input);},
  async bulkLifecycle(input:BulkLifecycleInput){const changed=[];const skipped=[];for(const id of input.employeeIds){const row=findEmployee(id);if(row.lifecycleStatus==="resigned"||row.transferClosure){skipped.push({id,reason:"Employee is closed"});continue}changed.push(await this.changeLifecycle(id,input.change))}return {changed,skipped};},
  async bulkUpdateOrganization(input:BulkOrganizationInput){await wait();required(input.reason,"Reason");const collection=input.field==="branchId"?employeeMasters.branches:input.field==="departmentId"?employeeMasters.departments:input.field==="designationId"?employeeMasters.designations:input.field==="weekOffMasterId"?employeeMasters.weekOffs:employeeMasters.holidayLists;const changed:Employee[]=[];const skipped:{id:string;reason:string}[]=[];for(const id of input.employeeIds){const row=findEmployee(id);if(row.lifecycleStatus==="resigned"||row.transferClosure){skipped.push({id,reason:"Employee is closed"});continue}const selected=master(collection,input.masterId,row.companyId);if(!selected){skipped.push({id,reason:"Master is inactive or belongs to another Company"});continue}const labelField=input.field==="branchId"?"branch":input.field==="departmentId"?"department":input.field==="designationId"?"designation":input.field==="weekOffMasterId"?"weekOffMaster":"holidayListMaster";const updated={...row,[input.field]:selected.id,[labelField]:selected.name,history:[...row.history,history(labelField,String(row[labelField]),selected.name,input.reason)],updatedAt:new Date().toISOString()} as Employee;employees=employees.map(employee=>employee.id===id?updated:employee);changed.push(updated)}return clone({changed,skipped})},
  async updateReportingManager(id:string,input:UpdateReportingManagerInput){await wait();required(input.reason,"Reason");const row=findEmployee(id);if(row.lifecycleStatus==="resigned"||row.transferClosure)throw new Error("Closed employees are read-only");if(input.reportingManagerId===id)throw new Error("Employee cannot report to themselves");const manager=input.reportingManagerId?findEmployee(input.reportingManagerId):undefined;if(manager&&manager.companyId!==row.companyId)throw new Error("Reporting Manager must belong to the same Company");const previous=row.reportingManager?.name??"None";const current=manager?.fullName??"None";const updated={...row,reportingManager:manager?{id:manager.id,name:manager.fullName}:undefined,history:[...row.history,history("reportingManager",previous,current,input.reason)],updatedAt:new Date().toISOString()};employees=employees.map(employee=>employee.id===id?updated:employee);return clone(updated)},
  async exportEmployees(input:EmployeeExportInput):Promise<EmployeeExportResult>{await wait();let rows=employees.filter(employee=>employee.companyId===input.companyId);if(input.scope==="selected")rows=rows.filter(employee=>input.employeeIds?.includes(employee.id));if(input.scope==="current"&&input.params){const result=await this.list({...input.params,page:1,pageSize:Number.MAX_SAFE_INTEGER});rows=result.items}const header=["Employee Code","Employee Name","Department","Designation","Branch","Joining Date","Status","Personal Email"];const values=rows.map(employee=>[employee.employeeCode,employee.fullName,employee.department,employee.designation,employee.branch,employee.joiningDate,employee.lifecycleStatus,employee.personalEmail]);const escaped=[header,...values].map(columns=>columns.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n");const label=input.scope==="selected"?"selected":input.scope==="all"?"all":"current";return {contents:escaped,fileName:`employees-${label}.${input.format==="excel"?"xls":input.format}`,mimeType:input.format==="pdf"?"text/plain":"text/csv",count:rows.length}},
  async transfer(id:string,input:TransferEmployeeInput){await wait();const source=findEmployee(id);if(source.lifecycleStatus==="resigned"||source.transferClosure)throw new Error("Employee is already closed");required(input.exitDate,"Exit/transfer date");required(input.joiningDate,"Destination joining date");const missing=[source.firstName,source.lastName,source.personalEmail,source.phone,source.dob,source.aadhaarName,source.aadhaarNumber,source.pan,source.emergencyContact.name,source.emergencyContact.phone,source.emergencyContact.relationship].some(value=>!value?.trim());if(missing)throw new Error("Complete all required Employee Create profile fields before transfer");if(input.destinationCompanyId===source.companyId)throw new Error("Choose a different destination company");const bankInput={accountNumber:"",accountHolder:"",bankName:"",branchName:"",ifsc:""};const destination=await this.create({companyId:input.destinationCompanyId,branchId:input.branchId,departmentId:input.departmentId,designationId:input.designationId,weekOffMasterId:input.weekOffMasterId,holidayListMasterId:input.holidayListMasterId,firstName:source.firstName,middleName:source.middleName,lastName:source.lastName,personalEmail:source.personalEmail,phone:source.phone,dob:source.dob,aadhaarName:source.aadhaarName,aadhaarNumber:source.aadhaarNumber,pan:source.pan,joiningDate:input.joiningDate,lifecycleStatus:"probation",permanentAddress:source.permanentAddress,correspondenceAddress:source.correspondenceAddress,emergencyContact:source.emergencyContact,bank:bankInput});banks.delete(destination.id);const closed={...source,endDate:input.exitDate,transferClosure:{destinationEmployeeId:destination.id,exitDate:input.exitDate},accountSummary:{...source.accountSummary,state:"disabled" as const},updatedAt:new Date().toISOString(),history:[...source.history,history("companyTransfer",source.company,destination.company,"Company transfer")]};employees=employees.map(e=>e.id===id?closed:e);return clone({source:closed,destination});},
  async bank(id: string) { await wait(); return clone(banks.get(id) ?? []); }, async statutory(id: string) { await wait(); return clone(statutory.get(id) ?? {}); },
};
