import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { queryKeys } from "@/shared/constants/query-keys";
import { empDocumentApi, type DocumentInput } from "../api/employee-document.api";
import type { DocumentCategoryType, DocumentType } from "../types/document.type";
export const useEmployeeDocuments=(employeeId:string)=>useQuery({queryKey:queryKeys.employee.documents(employeeId),queryFn:()=>empDocumentApi.getDocuments(employeeId),enabled:Boolean(employeeId)});
const useDocumentMutation=<T,>(employeeId:string,mutationFn:(input:T)=>Promise<unknown>)=>{const qc=useQueryClient();return useMutation({mutationFn,onSuccess:()=>qc.invalidateQueries({queryKey:queryKeys.employee.documents(employeeId)})})};
export const useUploadEmployeeDocument=(employeeId:string)=>useDocumentMutation<DocumentInput>(employeeId,input=>empDocumentApi.uploadDocument(employeeId,input));
export const useUpdateEmployeeDocument=(employeeId:string)=>useDocumentMutation<{id:string;document_category:DocumentCategoryType;document_name:DocumentType;document_description?:string}>(employeeId,input=>empDocumentApi.updateMetadata(employeeId,input.id,input));
export const useReplaceEmployeeDocument=(employeeId:string)=>useDocumentMutation<{id:string;file:File}>(employeeId,input=>empDocumentApi.replace(employeeId,input.id,input.file));
export const useArchiveEmployeeDocument=(employeeId:string)=>useDocumentMutation<{id:string;archived:boolean}>(employeeId,input=>empDocumentApi.setArchived(employeeId,input.id,input.archived));
