import { useState } from "react";
import { ArrowLeft, Eye, EyeOff, History, Pencil } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { useAuth } from "@/modules/auth/hooks/useAuth";
import { Button } from "@/shared/ui/button/Button";
import { Badge } from "@/shared/ui/badge/Badge";
import { Modal } from "@/shared/ui/modal/Modal";
import { PageSpinner } from "@/shared/ui/spinner/Spinner";
import { EmployeeDocumentStep } from "../forms/EmployeeDocumentStep";
import { useEmployee, useEmployeeBank, useEmployeeStatutory } from "../hooks/useEmployees";
import { LIFECYCLE_LABELS, type HistoryEntry } from "../types/employee.type";

const mask=(value?:string)=>value?`${"•".repeat(Math.max(4,value.length-4))}${value.slice(-4)}`:"Not recorded";
const Field=({label,value,history,onHistory}:{label:string;value?:string|number;history?:HistoryEntry[];onHistory?:(label:string,entries:HistoryEntry[])=>void})=><div><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 flex items-center gap-1 text-sm text-slate-700 dark:text-navy-100"><span>{value||"Not recorded"}</span>{Boolean(history?.length)&&<button type="button" className="rounded p-1 text-primary hover:bg-primary/10" aria-label={`View ${label} history`} onClick={()=>onHistory?.(label,history??[])}><History className="size-3.5"/></button>}</dd></div>;
const Card=({title,children}:{title:string;children:React.ReactNode})=><section className="card p-5"><h3 className="mb-4 font-semibold">{title}</h3><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{children}</dl></section>;
const EmployeeDetailPage=()=>{const {id}=useParams();const navigate=useNavigate();const {user}=useAuth();const employee=useEmployee(id);const isHr=user?.role==="hr";const isEmployee=user?.role==="employee";const canSensitive=isHr||isEmployee;const bank=useEmployeeBank(id,canSensitive);const statutory=useEmployeeStatutory(id,canSensitive);const [revealed,setRevealed]=useState(false);const [historyModal,setHistoryModal]=useState<{label:string;entries:HistoryEntry[]}|null>(null);
 if(employee.isLoading)return <PageSpinner/>;if(employee.isError||!employee.data)return <div className="card p-8 text-center"><p className="mb-3 text-error">Employee could not be loaded.</p><Button onClick={()=>employee.refetch()}>Retry</Button></div>;const e=employee.data;const sensitive=(value?:string)=>isHr||revealed?value||"Not recorded":mask(value);const histories=(...fields:string[])=>e.history.filter(entry=>fields.includes(entry.field));const open=(label:string,entries:HistoryEntry[])=>setHistoryModal({label,entries});const canEdit=isHr&&e.lifecycleStatus!=="resigned"&&!e.transferClosure;const employeeDocumentAccess=isEmployee&&!e.transferClosure&&(!e.endDate||new Date(`${e.endDate}T23:59:59`)>=new Date());
 return <div className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Button variant="ghost" onClick={()=>navigate("/employees/list/")}><ArrowLeft className="size-4"/></Button><div className="grid size-12 place-items-center rounded-full bg-primary/10 font-semibold text-primary">{e.firstName[0]}{e.lastName[0]}</div><div><h2 className="text-xl font-semibold">{e.fullName}</h2><div className="flex items-center gap-1 text-sm text-slate-500"><span>{e.employeeCode}</span>{histories("employeeCode").length>0&&<button aria-label="View Employee Code history" onClick={()=>open("Employee Code",histories("employeeCode"))}><History className="size-3.5 text-primary"/></button>}<span>· {e.designation}</span></div></div><div className="flex items-center gap-1"><Badge label={LIFECYCLE_LABELS[e.lifecycleStatus]} variant="primary"/>{histories("lifecycleStatus").length>0&&<button aria-label="View Lifecycle history" onClick={()=>open("Lifecycle Status",histories("lifecycleStatus"))}><History className="size-3.5 text-primary"/></button>}</div></div><div className="flex gap-2">{canSensitive&&<Button variant="outline" onClick={()=>setRevealed(value=>!value)} leftIcon={revealed?<EyeOff className="size-4"/>:<Eye className="size-4"/>}>{revealed?"Mask protected data":"Reveal protected data"}</Button>}{canEdit&&<Button onClick={()=>navigate(`/employees/list/${e.id}/edit`)} leftIcon={<Pencil className="size-4"/>}>Manage Employee</Button>}</div></header>
 <Card title="Employment and organization"><Field label="Company" value={e.company} history={histories("company","companyTransfer")} onHistory={open}/><Field label="Branch" value={e.branch} history={histories("branch")} onHistory={open}/><Field label="Department" value={e.department} history={histories("department")} onHistory={open}/><Field label="Designation" value={e.designation} history={histories("designation")} onHistory={open}/><Field label="Reporting Manager" value={e.reportingManager?.name} history={histories("reportingManager")} onHistory={open}/><Field label="Week Off Master" value={e.weekOffMaster}/><Field label="Holiday List" value={e.holidayListMaster}/><Field label="Joining Date" value={e.joiningDate}/></Card>
 <Card title="Personal profile"><Field label="Personal Email" value={e.personalEmail}/><Field label="Phone" value={e.phone}/><Field label="DOB" value={canSensitive?sensitive(e.dob):"Restricted"}/><Field label="Aadhaar Name" value={canSensitive?sensitive(e.aadhaarName):"Restricted"}/><Field label="Aadhaar Number" value={canSensitive?sensitive(e.aadhaarNumber):"Restricted"}/><Field label="PAN" value={canSensitive?sensitive(e.pan):"Restricted"}/><Field label="Emergency Contact" value={`${e.emergencyContact.name} · ${e.emergencyContact.relationship}`}/></Card>
 {canSensitive&&<Card title="Bank and statutory"><Field label="Active Bank" value={bank.data?.find(account=>account.active)?.bankName} history={histories("bank")} onHistory={open}/><Field label="Account Number" value={sensitive(bank.data?.find(account=>account.active)?.accountNumber)}/><Field label="Bank History" value={isHr?`${Math.max(0,(bank.data?.length??0)-1)} previous account(s)`:"Restricted"}/><Field label="UAN" value={sensitive(statutory.data?.uan)}/><Field label="PF Number" value={sensitive(statutory.data?.pfNumber)}/><Field label="ESIC Number" value={sensitive(statutory.data?.esicNumber)}/></Card>}
 <Card title="Domain summaries"><Field label="Account" value={isHr||isEmployee?e.accountSummary.state.replaceAll("_"," "):"Restricted"}/><Field label="Payroll" value={isHr||isEmployee?e.payrollSummary.ctcLabel:"Restricted"}/><Field label="Attendance" value={`${e.attendanceSummary.presentDays} present · ${e.attendanceSummary.absentDays} absent`}/><Field label="Leave" value={`${e.leaveSummary.available} available · ${e.leaveSummary.pending} pending`}/><Field label="Assets" value={`${e.assetsSummary.assigned} assigned`}/></Card>
 {e.recruitmentProvenance&&<Card title="Recruitment provenance (read-only)"><Field label="Source" value={e.recruitmentProvenance.source}/><Field label="Candidate" value={e.recruitmentProvenance.candidateId}/><Field label="Offer" value={e.recruitmentProvenance.offerId}/></Card>}{(isHr||employeeDocumentAccess)&&<EmployeeDocumentStep employeeId={e.id} canManage={isHr} showArchived={isHr}/>} 
 <Modal isOpen={Boolean(historyModal)} onClose={()=>setHistoryModal(null)} title={`${historyModal?.label??"Field"} history`} size="lg"><div className="space-y-3">{historyModal?.entries.map(entry=><div key={entry.id} className="rounded-lg border border-slate-150 p-3"><p className="font-medium">Current: {entry.currentValue}</p><p className="text-sm">Previous: {entry.previousValue}</p><p className="text-xs text-slate-500">{entry.changedBy} · {new Date(entry.changedAt).toLocaleString()} {entry.reason&&`· ${entry.reason}`}</p></div>)}</div></Modal></div>;
};
export default EmployeeDetailPage;
