# Generated by Django 4.2.30 on 2026-07-21 03:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('country_id', models.PositiveIntegerField(blank=True, null=True)),
                ('state_id', models.PositiveIntegerField(blank=True, null=True)),
                ('city_id', models.PositiveIntegerField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=12)),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('reporting_manager', models.CharField(blank=True, max_length=150)),
                ('work_location', models.CharField(max_length=150)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('intern', 'Intern')], max_length=20)),
                ('date_of_joining', models.DateField()),
                ('annual_salary', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_candidate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_record', to='recruitment.candidate')),
                ('source_offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_record', to='recruitment.offer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
