# Generated by Django 4.2.30 on 2026-07-21 03:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('source', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=10)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('country_id', models.PositiveIntegerField(blank=True, null=True)),
                ('state_id', models.PositiveIntegerField(blank=True, null=True)),
                ('city_id', models.PositiveIntegerField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=12)),
                ('current_position', models.CharField(blank=True, max_length=150)),
                ('current_company', models.CharField(blank=True, max_length=150)),
                ('current_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notice_period', models.PositiveSmallIntegerField(blank=True, help_text='Days', null=True)),
                ('total_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('highest_education', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resume_url', models.URLField(blank=True, max_length=500, null=True)),
                ('referenced_by', models.CharField(blank=True, max_length=150)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('portfolio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('onboarding', 'Onboarding'), ('hired', 'Hired'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=20)),
                ('converted_to_employee', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('experience', models.PositiveSmallIntegerField(default=0)),
                ('location', models.CharField(max_length=150)),
                ('openings', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('on_hold', 'On hold')], db_index=True, default='draft', max_length=20)),
                ('closing_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_salary', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(1)])),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.CharField(choices=[('hr_round', 'HR round'), ('technical_round', 'Technical round'), ('managerial_round', 'Managerial round')], max_length=30)),
                ('interviewer', models.CharField(max_length=150)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'In person')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], db_index=True, default='scheduled', max_length=20)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='recruitment.job'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('job', 'email'), name='unique_candidate_email_per_job'),
        ),
    ]
