import { useState } from "react";
import { Download, FileText, History, Upload } from "lucide-react";
import { Button } from "@/shared/ui/button/Button";
import EmptyState from "@/shared/ui/empty-state/EmptyState";
import { Input } from "@/shared/ui/input/Input";
import { Modal } from "@/shared/ui/modal/Modal";
import { Select } from "@/shared/ui/select/Select";
import { Textarea } from "@/shared/ui/textarea/Textarea";
import { DOCUMENT_CATEGORY_OPTIONS, DOCUMENT_TYPE_OPTIONS, type DocumentCategoryType, type DocumentType, type EmployeeDocument } from "../types/document.type";
import { useArchiveEmployeeDocument, useEmployeeDocuments, useReplaceEmployeeDocument, useUpdateEmployeeDocument, useUploadEmployeeDocument } from "../hooks/useEmployeeDocuments";

export const EmployeeDocumentStep=({employeeId,canManage,showArchived=false}:{employeeId:string;canManage:boolean;showArchived?:boolean})=>{
 const query=useEmployeeDocuments(employeeId);const upload=useUploadEmployeeDocument(employeeId);const update=useUpdateEmployeeDocument(employeeId);const replace=useReplaceEmployeeDocument(employeeId);const archive=useArchiveEmployeeDocument(employeeId);
 const [uploadOpen,setUploadOpen]=useState(false);const [editing,setEditing]=useState<EmployeeDocument|null>(null);const [history,setHistory]=useState<EmployeeDocument|null>(null);const [category,setCategory]=useState<DocumentCategoryType>("resume");const [name,setName]=useState<DocumentType>("resume");const [description,setDescription]=useState("");const [file,setFile]=useState<File>();
 const rows=(query.data??[]).filter(item=>showArchived||!item.archived);const beginEdit=(document:EmployeeDocument)=>{setEditing(document);setCategory(document.document_category);setName(document.document_name);setDescription(document.document_description??"")};
 const save=(document:EmployeeDocument)=>{const url=URL.createObjectURL(new Blob([`Mock document: ${document.file_name}\nVersion ${document.version}`]));const link=window.document.createElement("a");link.href=url;link.download=document.file_name;link.click();URL.revokeObjectURL(url)};
 if(query.isLoading)return <section className="card p-8 text-center">Loading documents…</section>;if(query.isError)return <section className="card p-8 text-center"><p className="mb-3 text-error">Unable to load documents.</p><Button onClick={()=>query.refetch()}>Retry</Button></section>;
 return <section className="card p-5"><div className="mb-4 flex justify-between"><div><h3 className="font-semibold">Documents</h3><p className="text-xs text-slate-500">Employment-specific · PDF/DOC/DOCX/ODT/JPG/PNG · 10 MB max</p></div>{canManage&&<Button size="sm" leftIcon={<Upload className="size-4"/>} onClick={()=>setUploadOpen(true)}>Upload</Button>}</div>
 {!rows.length?<EmptyState icon={FileText} title="No documents found" description="Active Employee documents will appear here."/>:<div className="divide-y divide-slate-100">{rows.map(document=><div key={document.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{document.document_name.replaceAll("_"," ")}</p><p className="text-xs text-slate-500">{document.file_name} · v{document.version} · {document.archived?"Archived":"Active"}</p><p className="text-xs text-slate-400">{document.document_description}</p></div><div className="flex flex-wrap gap-1"><Button size="sm" variant="ghost" onClick={()=>save(document)} leftIcon={<Download className="size-3"/>}>Download</Button><Button size="sm" variant="ghost" onClick={()=>setHistory(document)} leftIcon={<History className="size-3"/>}>Versions</Button>{canManage&&<><Button size="sm" variant="ghost" onClick={()=>beginEdit(document)}>Edit metadata</Button><label className="btn cursor-pointer px-3 py-1.5 text-xs text-primary">Replace<input className="hidden" type="file" accept=".pdf,.doc,.docx,.odt,.jpg,.jpeg,.png" onChange={event=>{const next=event.target.files?.[0];if(next)replace.mutate({id:document.id,file:next})}}/></label><Button size="sm" variant="ghost" onClick={()=>archive.mutate({id:document.id,archived:!document.archived})}>{document.archived?"Restore":"Archive"}</Button></>}</div></div>)}</div>}
 <Modal isOpen={uploadOpen} onClose={()=>setUploadOpen(false)} title="Upload Employee document" footer={<><Button variant="outline" onClick={()=>setUploadOpen(false)}>Cancel</Button><Button disabled={!file} isLoading={upload.isPending} onClick={()=>file&&upload.mutate({document_category:category,document_name:name,document_description:description,file},{onSuccess:()=>{setUploadOpen(false);setFile(undefined)}})}>Upload</Button></>}><MetadataFields category={category} name={name} description={description} setCategory={setCategory} setName={setName} setDescription={setDescription}/><Input required label="File" type="file" accept=".pdf,.doc,.docx,.odt,.jpg,.jpeg,.png" onChange={event=>setFile(event.target.files?.[0])}/>{upload.error instanceof Error&&<p className="text-sm text-error">{upload.error.message}</p>}</Modal>
 <Modal isOpen={Boolean(editing)} onClose={()=>setEditing(null)} title="Edit document metadata" footer={<><Button variant="outline" onClick={()=>setEditing(null)}>Cancel</Button><Button isLoading={update.isPending} onClick={()=>editing&&update.mutate({id:editing.id,document_category:category,document_name:name,document_description:description},{onSuccess:()=>setEditing(null)})}>Save metadata</Button></>}><MetadataFields category={category} name={name} description={description} setCategory={setCategory} setName={setName} setDescription={setDescription}/>{update.error instanceof Error&&<p className="text-sm text-error">{update.error.message}</p>}</Modal>
 <Modal isOpen={Boolean(history)} onClose={()=>setHistory(null)} title="Document version history"><div className="space-y-2">{history?.versions.map(version=><div key={version.version} className="rounded-lg border p-3 text-sm"><strong>Version {version.version}</strong> · {version.file_name}<p className="text-xs text-slate-500">{version.uploaded_by} · {new Date(version.uploaded_at).toLocaleString()}</p></div>)}</div></Modal></section>;
};
const MetadataFields=({category,name,description,setCategory,setName,setDescription}:{category:DocumentCategoryType;name:DocumentType;description:string;setCategory:(value:DocumentCategoryType)=>void;setName:(value:DocumentType)=>void;setDescription:(value:string)=>void})=><div className="space-y-4"><Select required label="Category" options={DOCUMENT_CATEGORY_OPTIONS.map(item=>({value:item.value,label:item.label}))} value={category} onChange={event=>setCategory(event.target.value as DocumentCategoryType)}/><Select required label="Name" options={DOCUMENT_TYPE_OPTIONS.filter(item=>item.category_id===DOCUMENT_CATEGORY_OPTIONS.find(option=>option.value===category)?.category_id).map(item=>({value:item.value,label:item.label}))} value={name} onChange={event=>setName(event.target.value as DocumentType)}/><Textarea label="Description" value={description} onChange={event=>setDescription(event.target.value)}/></div>;
export default EmployeeDocumentStep;
