import { addAudit, attendanceRecords, audits, ATTENDANCE_TODAY, clone, delay, managerTeams, mockActors, mockBranches, mockEmployees, regularizations, replaceRecords, replaceRegularizations } from "./attendance.mock";
import type { AttendanceActor, AttendanceAudit, AttendanceListParams, AttendanceRecord, AttendanceResolution, BulkAttendanceInput, ClockInPayload, GeofenceOverrideInput, GeofenceResult, ManualAttendanceInput, MonthlyAttendanceInput, RegularizationInput } from "../types/attendance.types";

let context={companyId:1,actor:mockActors[3]};
export const setAttendanceMockContext=(companyId:number,actor:AttendanceActor)=>{context={companyId,actor}};
const fail=(code:string,message:string):never=>{const error=new Error(message) as Error&{code:string};error.code=code;throw error};
const employee=(id:string)=>mockEmployees.find(e=>e.id===id)??fail("NOT_FOUND","Employee not found");
const ownEmployee=()=>context.actor.employeeId??(context.actor.role==="hr"?(context.companyId===2?"emp-6":"emp-2"):fail("FORBIDDEN","No mock Employee identity is mapped"));
const scopeIds=()=>context.actor.role==="hr"?mockEmployees.filter(e=>e.companyId===context.companyId).map(e=>e.id):context.actor.role==="manager"?[context.actor.employeeId!,...(managerTeams[context.actor.employeeId!]??[])]:[ownEmployee()];
const scoped=(id:string)=>{const e=employee(id);if(e.companyId!==context.companyId)fail("COMPANY_SCOPE_ERROR","Employee belongs to another Company");if(!scopeIds().includes(id))fail("FORBIDDEN","Employee is outside the authorized Attendance scope");return e};
const branch=(id:string)=>mockBranches.find(b=>b.id===id&&b.companyId===context.companyId)??fail("INVALID_SCHEDULE","Branch Attendance configuration is unavailable");
const eligible=(id:string,date:string)=>{const e=scoped(id);if(e.lifecycleStatus==="resigned"||e.lifecycleStatus==="closed")fail("LIFECYCLE_NOT_ELIGIBLE","Employee lifecycle does not allow clocking");if(date<e.joiningDate||e.lastWorkingDate&&date>e.lastWorkingDate)fail("EMPLOYMENT_DATE_ERROR","Attendance date is outside the employment period");return e};
const localDate=(instant:string,timezone:string)=>new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(instant));
const deterministicInstant=(date:string,hour:number,minute:number)=>new Date(`${date}T${String(hour).padStart(2,"0")}:${String(minute).padStart(2,"0")}:00+05:30`).toISOString();
const minutes=(a:string|null,b:string|null)=>a&&b?Math.max(0,Math.round((new Date(b).getTime()-new Date(a).getTime())/60000)):0;
const timeMinutes=(instant:string,timezone:string)=>{const parts=new Intl.DateTimeFormat("en-US",{timeZone:timezone,hour12:false,hour:"2-digit",minute:"2-digit"}).formatToParts(new Date(instant));return Number(parts.find(p=>p.type==="hour")?.value)*60+Number(parts.find(p=>p.type==="minute")?.value)};
const audit=(before:AttendanceRecord,after:AttendanceRecord,reason:string,action:AttendanceAudit["action"],meta:Partial<AttendanceAudit>={})=>addAudit({id:`audit-${Date.now()}-${after.id}`,attendanceId:after.id,companyId:after.companyId,employeeId:after.employeeId,changedBy:context.actor.name,actorRole:context.actor.role,oldClockIn:before.clockInAt,newClockIn:after.clockInAt,oldClockOut:before.clockOutAt,newClockOut:after.clockOutAt,oldResult:before.result,newResult:after.result,reason,createdAt:new Date().toISOString(),action,...meta});
const blank=(id:string,date:string):AttendanceRecord=>{const e=scoped(id),b=branch(e.branchId);return{id:`att-${id}-${date}`,companyId:e.companyId,employeeId:id,employeeCode:e.employeeCode,employeeName:e.name,branchId:e.branchId,branch:e.branch,department:e.department,designation:e.designation,attendanceDate:date,appliedTimezone:b.timezone,dayType:"WORKING_DAY",result:"NO_RESULT",clockInAt:null,clockOutAt:null,workedMinutes:0,method:null,attributes:{late:false,earlyDeparture:false,remote:false,regularized:false,workedOnNonWorkingDay:false,manual:false},version:0}};
const calculate=(record:AttendanceRecord):AttendanceRecord=>{const policy=branch(record.branchId).lateEarly;if(!policy.enabled||!record.clockInAt)return{...record,attributes:{...record.attributes,late:false,earlyDeparture:false}};const expectedStart=Number(policy.expectedStart.slice(0,2))*60+Number(policy.expectedStart.slice(3)),expectedEnd=Number(policy.expectedEnd.slice(0,2))*60+Number(policy.expectedEnd.slice(3));const actualStart=timeMinutes(record.clockInAt,record.appliedTimezone),actualEnd=record.clockOutAt?timeMinutes(record.clockOutAt,record.appliedTimezone):null;const late=actualStart>expectedStart+policy.graceMinutes,early=actualEnd!==null&&actualEnd<expectedEnd-policy.graceMinutes;const half=(late&&policy.lateToHalfDay)||(early&&policy.earlyToHalfDay)||(policy.minimumHoursToHalfDay&&record.workedMinutes<policy.minimumHours*60&&Boolean(record.clockOutAt));return{...record,result:half?"HALF_DAY":record.clockOutAt?"PRESENT":record.result,attributes:{...record.attributes,late,earlyDeparture:early}}};
const save=(input:ManualAttendanceInput,action:AttendanceAudit["action"],allowApprover=false)=>{if(context.actor.role!=="hr"&&!allowApprover)fail("FORBIDDEN","HR authorization is required");if(!input.reason.trim())fail("VALIDATION_ERROR","Reason is required");const existing=attendanceRecords.find(r=>r.employeeId===input.employeeId&&r.attendanceDate===input.attendanceDate),before=existing??blank(input.employeeId,input.attendanceDate);let after:AttendanceRecord={...before,dayType:input.dayType??before.dayType,result:input.result,clockInAt:input.clockInAt||null,clockOutAt:input.clockOutAt||null,workedMinutes:minutes(input.clockInAt||null,input.clockOutAt||null),method:"HR_MANUAL",attributes:{...before.attributes,manual:true,regularized:action==="REGULARIZATION"||before.attributes.regularized,workedOnNonWorkingDay:(input.dayType??before.dayType)!=="WORKING_DAY"&&input.result==="PRESENT"},version:before.version+1};after=calculate(after);replaceRecords(existing?attendanceRecords.map(r=>r.id===existing.id?after:r):[...attendanceRecords,after]);audit(before,after,input.reason,action,{sourceMethod:"HR_MANUAL",approvalSource:input.approvalSource||undefined,approvalReference:input.approvalReference,approver:input.approver,approvalDate:input.approvalDate});return clone(after)};
const haversine=(a:number,b:number,c:number,d:number)=>{const r=6371e3,p=(n:number)=>n*Math.PI/180,x=p(c-a),y=p(d-b),h=Math.sin(x/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(y/2)**2;return 2*r*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))};
const legacy=(r:AttendanceRecord)=>({...r,employee_id:r.employeeId,attendance_date:r.attendanceDate,clock_in_at:r.clockInAt,clock_out_at:r.clockOutAt,clock_in_location:null,clock_out_location:null,clock_method:r.method==="REMOTE_GPS"?"remote":r.method?"office":null,status:r.regularizationStatus==="PENDING"?"regularization_pending":r.attributes.regularized?"regularized":r.dayType==="HOLIDAY"?"holiday":r.dayType==="WEEK_OFF"?"weekend":r.result.toLowerCase(),work_hours:r.workedMinutes/60,regularization_reason:null,regularization_requested_at:null});
const dates=(from:string,to:string)=>{const out:string[]=[];for(let d=new Date(`${from}T00:00:00Z`),end=new Date(`${to}T00:00:00Z`);d<=end;d.setUTCDate(d.getUTCDate()+1))out.push(d.toISOString().slice(0,10));return out};

type ScheduleAssignment={employeeId:string;masterId:string;from:string;to?:string;active:boolean;historical:boolean};
const weekAssignments:ScheduleAssignment[]=[{employeeId:"emp-1",masterId:"weekoff-current",from:"2026-01-01",active:true,historical:false},{employeeId:"emp-5",masterId:"weekoff-inactive-v1",from:"2025-01-01",to:"2026-12-31",active:false,historical:true}];
const holidayAssignments:ScheduleAssignment[]=[{employeeId:"emp-1",masterId:"holiday-2026",from:"2026-01-01",to:"2026-12-31",active:true,historical:false},{employeeId:"emp-5",masterId:"holiday-legacy-2026",from:"2026-01-01",to:"2026-12-31",active:false,historical:true}];
const assigned=(rows:ScheduleAssignment[],id:string,date:string)=>rows.find(a=>a.employeeId===id&&a.from<=date&&(!a.to||a.to>=date));

export const attendanceService={
 async listAttendance(p:AttendanceListParams){await delay();setAttendanceMockContext(p.companyId,p.actor);let rows=attendanceRecords.filter(r=>r.companyId===p.companyId&&scopeIds().includes(r.employeeId));const q=p.search.trim().toLowerCase();if(q)rows=rows.filter(r=>[r.employeeName,r.employeeCode,r.branch,r.department,r.designation].some(v=>v.toLowerCase().includes(q)));if(p.employeeId)rows=rows.filter(r=>r.employeeId===p.employeeId);if(p.dateFrom)rows=rows.filter(r=>r.attendanceDate>=p.dateFrom!);if(p.dateTo)rows=rows.filter(r=>r.attendanceDate<=p.dateTo!);if(p.results.length)rows=rows.filter(r=>p.results.includes(r.result));if(p.branch)rows=rows.filter(r=>r.branch===p.branch);if(p.department)rows=rows.filter(r=>r.department===p.department);if(p.designation)rows=rows.filter(r=>r.designation===p.designation);if(p.regularizationStatus)rows=rows.filter(r=>r.regularizationStatus===p.regularizationStatus);rows.sort((a,b)=>String(a[p.sortBy]).localeCompare(String(b[p.sortBy]))*(p.sortDirection==="asc"?1:-1));const start=(p.page-1)*p.pageSize;return clone({items:rows.slice(start,start+p.pageSize),total:rows.length,page:p.page,pageSize:p.pageSize})},
 async getAttendance(id:string){await delay();const row=attendanceRecords.find(r=>r.id===id)??fail("NOT_FOUND","Attendance record not found");scoped(row.employeeId);return clone(row)},
 async getTodayAttendance(){await delay();const id=ownEmployee();scoped(id);return legacy(clone(attendanceRecords.find(r=>r.employeeId===id&&r.attendanceDate===ATTENDANCE_TODAY)??blank(id,ATTENDANCE_TODAY)))},
 async getAttendanceHistory(month:number,year:number){await delay();const id=ownEmployee();return clone(attendanceRecords.filter(r=>r.employeeId===id&&r.attendanceDate.startsWith(`${year}-${String(month).padStart(2,"0")}`)))},async getAttendanceCalendar(month:number,year:number){return this.getAttendanceHistory(month,year)},
 async validateGeofence(branchId:string,p:ClockInPayload):Promise<GeofenceResult>{const b=branch(branchId);if(b.latitude===null||b.longitude===null||b.radiusMeters===null)return{allowed:false,distanceMeters:null,radiusMeters:null,accuracyAccepted:false,reason:"Invalid Branch geofence configuration"};if((p.accuracy??20)>100)return{allowed:false,distanceMeters:null,radiusMeters:b.radiusMeters,accuracyAccepted:false,reason:"Location accuracy is insufficient"};const d=Math.round(haversine(p.latitude,p.longitude,b.latitude,b.longitude));return{allowed:d<=b.radiusMeters,distanceMeters:d,radiusMeters:b.radiusMeters,accuracyAccepted:true,reason:d<=b.radiusMeters?"Within Branch geofence":"Outside Branch geofence"}},
 async clockIn(p:ClockInPayload){await delay();const id=ownEmployee(),e=scoped(id),b=branch(e.branchId),instant=deterministicInstant(ATTENDANCE_TODAY,9,32),date=localDate(instant,b.timezone);eligible(id,date);if(attendanceRecords.some(r=>r.employeeId===id&&r.attendanceDate===date&&r.clockInAt))fail("ALREADY_CLOCKED_IN","Employee has already clocked in");const method=p.method??"OFFICE_GPS";if(method==="REMOTE_GPS"&&(!e.remoteClockApproved||!e.wfhApproved))fail("REMOTE_NOT_AUTHORIZED","Remote clock is not approved");if(method==="OFFICE_GPS"){const geo=await this.validateGeofence(e.branchId,p);if(!geo.allowed)fail("GEOFENCE_FAILED",geo.reason)}const before=blank(id,date),after=calculate({...before,clockInAt:instant,method,attributes:{...before.attributes,remote:method==="REMOTE_GPS"},version:1});replaceRecords([...attendanceRecords,after]);audit(before,after,"Employee clock in","CLOCK_IN",{sourceMethod:method});return{message:"Clock in successful",attendance:legacy(after)}},
 async clockOut(p:ClockInPayload){await delay();const id=ownEmployee(),e=scoped(id),b=branch(e.branchId),instant=deterministicInstant(ATTENDANCE_TODAY,18,12),date=localDate(instant,b.timezone);eligible(id,date);const open=attendanceRecords.find(r=>r.employeeId===id&&r.clockInAt&&!r.clockOutAt)??fail("NO_OPEN_SESSION","No open Attendance session found");if(open.attendanceDate!==date)fail("NO_OVERNIGHT_ATTENDANCE","Clock-out must occur on the same Branch-timezone business date");if((p.method??open.method)==="OFFICE_GPS"){const geo=await this.validateGeofence(e.branchId,p);if(!geo.allowed)fail("GEOFENCE_FAILED",geo.reason)}const before=clone(open),after=calculate({...open,clockOutAt:instant,workedMinutes:minutes(open.clockInAt,instant),version:open.version+1});replaceRecords(attendanceRecords.map(r=>r.id===open.id?after:r));audit(before,after,"Employee clock out","CLOCK_OUT",{sourceMethod:after.method??undefined});return{message:"Clock out successful",attendance:legacy(after)}},
 async createRegularization(input:RegularizationInput){await delay();const id=ownEmployee(),e=scoped(id);if(e.lifecycleStatus==="closed")fail("LIFECYCLE_NOT_ELIGIBLE","Closed Employees cannot submit regularization");if(!input.reason.trim())fail("VALIDATION_ERROR","Reason is required");if(regularizations.some(r=>r.employeeId===id&&r.attendanceDate===input.attendance_date&&r.status==="PENDING"))fail("DUPLICATE_REGULARIZATION","A pending request already exists");const now=new Date().toISOString(),row={id:`reg-${Date.now()}`,companyId:e.companyId,employeeId:id,employeeName:e.name,attendanceDate:input.attendance_date,reasonType:input.reasonType??"PUNCH_ISSUE",reason:input.reason,requestedClockIn:input.requested_clock_in,requestedClockOut:input.requested_clock_out,status:"PENDING" as const,requestedBy:e.name,createdAt:now,updatedAt:now,version:1};replaceRegularizations([...regularizations,row]);return clone(row)},
 async listRegularizations(){await delay();return clone(regularizations.filter(r=>r.companyId===context.companyId&&scopeIds().includes(r.employeeId)))},async cancelRegularization(id:string){const row=regularizations.find(r=>r.id===id)??fail("NOT_FOUND","Regularization not found");if(row.employeeId!==ownEmployee()||row.status!=="PENDING")fail("REGULARIZATION_STATE_ERROR","Only your pending request can be cancelled");const next={...row,status:"CANCELLED" as const,updatedAt:new Date().toISOString(),version:row.version+1};replaceRegularizations(regularizations.map(r=>r.id===id?next:r));return clone(next)},
 async decideRegularization(id:string,status:"APPROVED"|"REJECTED",reason:string){if(context.actor.role==="employee")fail("FORBIDDEN","Approval authorization is required");const row=regularizations.find(r=>r.id===id)??fail("NOT_FOUND","Regularization not found");scoped(row.employeeId);if(row.status!=="PENDING")fail("REGULARIZATION_STATE_ERROR","Request is not pending");const next={...row,status,decisionReason:reason,decidedBy:context.actor.name,updatedAt:new Date().toISOString(),version:row.version+1};replaceRegularizations(regularizations.map(r=>r.id===id?next:r));if(status==="APPROVED")save({employeeId:row.employeeId,attendanceDate:row.attendanceDate,clockInAt:row.requestedClockIn,clockOutAt:row.requestedClockOut,result:"PRESENT",reason:`Approved regularization: ${reason}`},"REGULARIZATION",true);return clone(next)},async approveRegularization(id:string,reason:string){return this.decideRegularization(id,"APPROVED",reason)},async rejectRegularization(id:string,reason:string){return this.decideRegularization(id,"REJECTED",reason)},
 async createAttendance(i:ManualAttendanceInput){return save(i,"MANUAL_CORRECTION")},async correctAttendance(i:ManualAttendanceInput){return save(i,"MANUAL_CORRECTION")},async reopenAttendance(i:ManualAttendanceInput){return save(i,"REOPEN")},
 async overrideGeofence(i:GeofenceOverrideInput){if(context.actor.role!=="hr")fail("FORBIDDEN","HR authorization is required");if(!i.reason.trim())fail("VALIDATION_ERROR","Reason is required");const before=attendanceRecords.find(r=>r.employeeId===i.employeeId&&r.attendanceDate===i.attendanceDate)??blank(i.employeeId,i.attendanceDate);audit(before,before,i.reason,"GEOFENCE_OVERRIDE",{geofenceEvidence:`${i.originalResult}; override=${i.overrideAllowed}`,sourceMethod:"HR_MANUAL"});return clone(before)},
 async bulkAttendance(i:BulkAttendanceInput){if(context.actor.role!=="hr")fail("FORBIDDEN","HR authorization is required");if(!i.reason.trim())fail("VALIDATION_ERROR","Reason is required");const pairs=i.employeeIds.flatMap(id=>dates(i.dateFrom,i.dateTo).map(date=>({id,date})));const results=pairs.map(x=>{const e=scoped(x.id);if(e.lifecycleStatus==="resigned"||e.lifecycleStatus==="closed")return{employeeId:x.id,attendanceDate:x.date,success:false,message:"Lifecycle skipped"};if(!i.preview)save({employeeId:x.id,attendanceDate:x.date,result:i.result,reason:i.reason},"BULK");return{employeeId:x.id,attendanceDate:x.date,success:true,message:i.preview?"Ready":"Applied"}});if(i.preview)return{confirmationId:`confirm-${pairs.length}`,previewCount:pairs.length,results};if(!i.confirmationId)fail("VALIDATION_ERROR","Preview confirmation is required");return{previewCount:pairs.length,results}},
 async getMonthlyAttendance(id:string,year:number,month:number){await delay();scoped(id);const end=new Date(Date.UTC(year,month,0)).getUTCDate(),rows:AttendanceRecord[]=[];for(let day=1;day<=end;day++){const date=`${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`;let row=attendanceRecords.find(r=>r.employeeId===id&&r.attendanceDate===date)??blank(id,date);const resolved=await this.resolveDayClassification(id,date);row={...row,dayType:resolved.dayType,attributes:{...row.attributes,workedOnNonWorkingDay:resolved.dayType!=="WORKING_DAY"&&row.result==="PRESENT"}};rows.push(row)}return clone(rows)},async saveMonthlyAttendance(i:MonthlyAttendanceInput){if(context.actor.role!=="hr")fail("FORBIDDEN","HR authorization is required");return i.changes.map(c=>save({employeeId:i.employeeId,attendanceDate:c.attendanceDate,result:c.result,reason:c.reason},"MONTHLY_EDIT"))},
 async getHistory(id?:string){await delay();return clone(audits.filter(a=>a.companyId===context.companyId&&scopeIds().includes(a.employeeId)&&(!id||a.attendanceId===id)))},
 async exportAttendance(p:AttendanceListParams){const result=await this.listAttendance({...p,page:1,pageSize:Number.MAX_SAFE_INTEGER});const rows=[["Employee Code","Employee","Date","Day Type","Result","Clock In","Clock Out","Worked Minutes","Method"],...result.items.map(r=>[r.employeeCode,r.employeeName,r.attendanceDate,r.dayType,r.result,r.clockInAt??"",r.clockOutAt??"",String(r.workedMinutes),r.method??""])];return{fileName:"attendance.csv",contents:rows.map(cols=>cols.map(v=>`"${v.replaceAll('"','""')}"`).join(",")).join("\n"),count:result.total}},
 async resolveWeekOff(id:string,date:string):Promise<AttendanceResolution>{scoped(id);const a=assigned(weekAssignments,id,date);const sunday=new Date(`${date}T00:00:00Z`).getUTCDay()===0;return{dayType:a&&sunday?"WEEK_OFF":"WORKING_DAY",reference:a?.masterId??"no-weekoff-assignment",historical:Boolean(a?.historical)}},
 async resolveHoliday(id:string,date:string):Promise<AttendanceResolution>{scoped(id);const a=assigned(holidayAssignments,id,date),holiday=Boolean(a&&["2026-08-15","2026-08-26"].includes(date));return{dayType:holiday?"HOLIDAY":"WORKING_DAY",reference:a?.masterId??"no-holiday-assignment",historical:Boolean(a?.historical)}},
 async resolveDayClassification(id:string,date:string){const holiday=await this.resolveHoliday(id,date);if(holiday.dayType==="HOLIDAY")return holiday;return this.resolveWeekOff(id,date)},async resolveBranchTimezone(id:string){return branch(id).timezone},async resolveAttendancePolicy(id:string){const e=scoped(id);return{punchRequirement:e.punchRequirement,lateEarly:branch(e.branchId).lateEarly}},async employees(){await delay();return clone(mockEmployees.filter(e=>e.companyId===context.companyId&&scopeIds().includes(e.id)))}
};
