import type { AttendanceActor, AttendanceAudit, AttendanceEmployee, AttendanceRecord, BranchAttendanceConfig, RegularizationRequest } from "../types/attendance.types";
export const ATTENDANCE_TODAY="2026-08-27";
export const mockActors:Record<number,AttendanceActor>={1:{userId:1,role:"hr",name:"HR Administrator"},2:{userId:2,role:"manager",employeeId:"emp-2",name:"People Manager"},3:{userId:3,role:"employee",employeeId:"emp-1",name:"Employee User"}};
export const mockEmployees:AttendanceEmployee[]=[
{id:"emp-1",companyId:1,employeeCode:"PPT-0001",name:"Aarav Mehta",branchId:"b1",branch:"Ahmedabad",department:"Engineering",designation:"Software Engineer",lifecycleStatus:"regular",joiningDate:"2024-01-10",remoteClockApproved:true,wfhApproved:true,punchRequirement:"PUNCH_REQUIRED",managerId:"emp-2"},
{id:"emp-2",companyId:1,employeeCode:"PPT-0002",name:"Meera Shah",branchId:"b1",branch:"Ahmedabad",department:"People Operations",designation:"HR Executive",lifecycleStatus:"probation",joiningDate:"2026-06-01",remoteClockApproved:false,wfhApproved:false,punchRequirement:"PUNCH_REQUIRED"},
{id:"emp-3",companyId:1,employeeCode:"PPT-0003",name:"Kabir Patel",branchId:"b2",branch:"Mumbai",department:"Engineering",designation:"Lead Engineer",lifecycleStatus:"notice_period",joiningDate:"2022-04-01",lastWorkingDate:"2026-09-15",remoteClockApproved:false,wfhApproved:false,punchRequirement:"PUNCH_REQUIRED",managerId:"emp-2"},
{id:"emp-4",companyId:1,employeeCode:"PPT-0004",name:"Nisha Rao",branchId:"b1",branch:"Ahmedabad",department:"Finance",designation:"Analyst",lifecycleStatus:"resigned",joiningDate:"2021-01-01",lastWorkingDate:"2026-07-31",remoteClockApproved:false,wfhApproved:false,punchRequirement:"PUNCH_REQUIRED"},
{id:"emp-5",companyId:1,employeeCode:"PPT-0005",name:"Dev Joshi",branchId:"b3",branch:"Vadodara Legacy",department:"Operations",designation:"Consultant",lifecycleStatus:"temp",joiningDate:"2025-01-01",remoteClockApproved:false,wfhApproved:false,punchRequirement:"PUNCH_OPTIONAL",managerId:"emp-2"},
{id:"emp-7",companyId:1,employeeCode:"PPT-0007",name:"Riya Sen",branchId:"b1",branch:"Ahmedabad",department:"Finance",designation:"Director",lifecycleStatus:"closed",joiningDate:"2020-01-01",lastWorkingDate:"2026-06-30",remoteClockApproved:false,wfhApproved:false,punchRequirement:"PUNCH_OPTIONAL"},
{id:"emp-6",companyId:2,employeeCode:"NSS-0001",name:"Ira Nair",branchId:"b4",branch:"Bengaluru",department:"Customer Success",designation:"Success Manager",lifecycleStatus:"regular",joiningDate:"2024-02-01",remoteClockApproved:true,wfhApproved:true,punchRequirement:"PUNCH_REQUIRED"}];
export const mockBranches:BranchAttendanceConfig[]=[
{id:"b1",companyId:1,name:"Ahmedabad",timezone:"Asia/Kolkata",latitude:22.3072,longitude:73.1812,radiusMeters:250,lateEarly:{enabled:true,expectedStart:"09:30",expectedEnd:"18:30",graceMinutes:15,lateToHalfDay:true,minimumHoursToHalfDay:true,minimumHours:6,earlyToHalfDay:false}},
{id:"b2",companyId:1,name:"Mumbai",timezone:"Asia/Kolkata",latitude:19.076,longitude:72.8777,radiusMeters:300,lateEarly:{enabled:true,expectedStart:"10:00",expectedEnd:"19:00",graceMinutes:10,lateToHalfDay:false,minimumHoursToHalfDay:true,minimumHours:5,earlyToHalfDay:false}},
{id:"b3",companyId:1,name:"Vadodara Legacy",timezone:"Asia/Kolkata",latitude:null,longitude:null,radiusMeters:null,lateEarly:{enabled:false,expectedStart:"09:30",expectedEnd:"18:30",graceMinutes:0,lateToHalfDay:false,minimumHoursToHalfDay:false,minimumHours:0,earlyToHalfDay:false}},
{id:"b4",companyId:2,name:"Bengaluru",timezone:"Asia/Kolkata",latitude:12.9716,longitude:77.5946,radiusMeters:200,lateEarly:{enabled:false,expectedStart:"09:00",expectedEnd:"18:00",graceMinutes:0,lateToHalfDay:false,minimumHoursToHalfDay:false,minimumHours:0,earlyToHalfDay:false}}];
const attrs={late:false,earlyDeparture:false,remote:false,regularized:false,workedOnNonWorkingDay:false,manual:false};
const row=(id:string,employeeId:string,date:string,result:AttendanceRecord["result"],dayType:AttendanceRecord["dayType"],extra:Partial<AttendanceRecord>={}):AttendanceRecord=>{const e=mockEmployees.find(x=>x.id===employeeId)!;return{id,companyId:e.companyId,employeeId,employeeCode:e.employeeCode,employeeName:e.name,branchId:e.branchId,branch:e.branch,department:e.department,designation:e.designation,attendanceDate:date,appliedTimezone:"Asia/Kolkata",dayType,result,clockInAt:result==="PRESENT"||result==="HALF_DAY"?`${date}T09:30:00+05:30`:null,clockOutAt:result==="PRESENT"?`${date}T18:15:00+05:30`:result==="HALF_DAY"?`${date}T14:00:00+05:30`:null,workedMinutes:result==="PRESENT"?525:result==="HALF_DAY"?270:0,method:result==="PRESENT"||result==="HALF_DAY"?"OFFICE_GPS":null,attributes:{...attrs},version:1,...extra}};
export let attendanceRecords:AttendanceRecord[]=[row("att-1","emp-1","2026-08-24","PRESENT","WORKING_DAY"),row("att-2","emp-1","2026-08-25","HALF_DAY","WORKING_DAY",{attributes:{...attrs,regularized:true},regularizationStatus:"APPROVED",leaveReference:"leave-half-1"}),row("att-3","emp-1","2026-08-26","NO_RESULT","HOLIDAY"),row("att-4","emp-2","2026-08-26","PRESENT","WORKING_DAY"),row("att-5","emp-3","2026-08-26","ABSENT","WORKING_DAY"),row("att-6","emp-4","2026-07-30","PRESENT","WORKING_DAY"),row("att-7","emp-5","2026-08-23","PRESENT","WEEK_OFF",{method:"HR_MANUAL",attributes:{...attrs,manual:true,workedOnNonWorkingDay:true}}),row("att-8","emp-6","2026-08-26","PRESENT","WORKING_DAY"),row("att-9","emp-7","2026-06-29","PRESENT","WORKING_DAY")];
export let regularizations:RegularizationRequest[]=[{id:"reg-1",companyId:1,employeeId:"emp-1",employeeName:"Aarav Mehta",attendanceId:"att-2",attendanceDate:"2026-08-25",reasonType:"INCORRECT_CLOCK_TIME",reason:"Client punch issue",requestedClockIn:"2026-08-25T09:30:00+05:30",requestedClockOut:"2026-08-25T18:00:00+05:30",status:"APPROVED",requestedBy:"Aarav Mehta",createdAt:"2026-08-26T09:00:00Z",updatedAt:"2026-08-26T11:00:00Z",decidedBy:"HR Administrator",version:2},{id:"reg-2",companyId:1,employeeId:"emp-3",employeeName:"Kabir Patel",attendanceId:"att-5",attendanceDate:"2026-08-26",reasonType:"MISSING_CLOCK_IN",reason:"Device was unavailable",requestedClockIn:"2026-08-26T10:00:00+05:30",requestedClockOut:"2026-08-26T19:00:00+05:30",status:"PENDING",requestedBy:"Kabir Patel",createdAt:"2026-08-27T05:00:00Z",updatedAt:"2026-08-27T05:00:00Z",version:1},{id:"reg-3",companyId:1,employeeId:"emp-1",employeeName:"Aarav Mehta",attendanceDate:"2026-08-20",reasonType:"PUNCH_ISSUE",reason:"Incorrect device punch",status:"REJECTED",requestedBy:"Aarav Mehta",createdAt:"2026-08-21T05:00:00Z",updatedAt:"2026-08-21T08:00:00Z",decisionReason:"Insufficient evidence",version:2},{id:"reg-4",companyId:1,employeeId:"emp-1",employeeName:"Aarav Mehta",attendanceDate:"2026-08-19",reasonType:"MISSING_CLOCK_OUT",reason:"Forgot to clock out",status:"CANCELLED",requestedBy:"Aarav Mehta",createdAt:"2026-08-20T05:00:00Z",updatedAt:"2026-08-20T06:00:00Z",version:2}];
export let audits:AttendanceAudit[]=[{id:"audit-1",attendanceId:"att-2",companyId:1,employeeId:"emp-1",changedBy:"HR Administrator",actorRole:"hr",oldClockIn:"2026-08-25T10:20:00+05:30",newClockIn:"2026-08-25T09:30:00+05:30",oldClockOut:"2026-08-25T14:00:00+05:30",newClockOut:"2026-08-25T18:00:00+05:30",oldResult:"HALF_DAY",newResult:"HALF_DAY",reason:"Approved regularization",createdAt:"2026-08-26T11:00:00Z",action:"REGULARIZATION"}];
export const managerTeams:Record<string,string[]>={"emp-2":["emp-1","emp-3","emp-5"]};
export const clone=<T,>(v:T):T=>structuredClone(v);export const delay=()=>new Promise(r=>setTimeout(r,120));export const replaceRecords=(v:AttendanceRecord[])=>{attendanceRecords=v};export const replaceRegularizations=(v:RegularizationRequest[])=>{regularizations=v};export const addAudit=(v:AttendanceAudit)=>{audits=[v,...audits]};
